"""add orders and order_items

Revision ID: cd31e7501269
Revises: a318d57a6ea8
Create Date: 2026-01-25 20:13:54.041833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd31e7501269'
down_revision: Union[str, Sequence[str], None] = 'a318d57a6ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_column('order_items', 'unit_ptice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('unit_ptice', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'product_id')
    # ### end Alembic commands ###
